name: CI

on:
  push:
  pull_request:
    branches:
      - default

  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: test/test.ps1
